# Generated by Django 6.0.2 on 2026-03-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
