# Generated by Django 6.0.2 on 2026-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_phone_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
